name: Deploy Java App to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: $\{{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: $\{{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL }}:latest .
          aws ecr get-login-password --region $\{{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $\{{ secrets.ECR_REPO_URL }}
          docker push ${{ secrets.ECR_REPO_URL }}:latest

      - name: Deploy to Kubernetes using Helm
        run: |
          helm upgrade --install my-java-app ./helm --namespace default --set image.repository=${{ secrets.ECR_REPO_URL }}:latest
